name: Cocoapods

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pod install
      run: pod install --repo-update
      working-directory: ./Example
    - name: Build
      run: xcodebuild
          -workspace SwiftConfetti.xcworkspace
          -scheme SwiftConfetti-Example
          -sdk iphonesimulator
           build
      working-directory: ./Example
    - name: Lint
      run: pod lib lint
